language: node_js
node_js:
   - "0.10"
   - "0.11"
   - "0.12"
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=yo77hhrMTw5gZ9NOmOqKiY99BLWN2pFgG node_modules/.bin/alinex-make test -c --coveralls